var members  = [
    {
        id:1,
        name_cn: "熊沢 世莉奈",
        position_cn: "一期生 Team KIV 1997年4月17日 福岡県",
        img_sm:"./img/hkt_pic/team_m1.png",
        img_lg:"./img/hkt_pic/team_1.png",
        alt_cn:"熊沢 世莉奈 - 一期生 Team KIV 1997年4月17日 福岡県",
        introdution_cn:"SERINA KUMAZAWA<br>Team KIV<br>ニックネーム：せりーぬ<br>生年月日：1997年4月17日<br>血液型：O<br>出身地：福岡県<br>身長：164cm<br>趣味：イラスト書き<br>特技：アクロバット<br>チャームポイント：笑顔",
    },
    {
        id:2,
        name_cn: "松岡 菜摘",
        position_cn: "一期生 Team H 1996年8月8日 福岡県",
        img_sm:"./img/hkt_pic/team_m2.png",
        img_lg:"./img/hkt_pic/team_2.png",
        alt_cn:"松岡 菜摘 - 一期生 Team H 1996年8月8日 福岡県",
        introdution_cn:"NATSUMI MATSUOKA<br>HKT48 Team H キャプテン<br>ニックネーム：なつ<br>生年月日：1996年8月8日<br>血液型：A<br>出身地：福岡県<br>身長：161cm<br>趣味：甘いものを食べること<br>特技：糸電話<br>チャームポイント：まつげ",
    },
    {
        id:3,
        name_cn: "栗原 紗英",
        position_cn: "三期生 Team TII 1996年6月20日 福岡県",
        img_sm:"./img/hkt_pic/team_m3.png",
        img_lg:"./img/hkt_pic/team_3.png",
        alt_cn:"栗原 紗英 - 三期生 Team TII 1996年6月20日 福岡県",
        introdution_cn:"SAE KURIHARA<br>Team TII<br>ニックネーム：さえちゃん<br>生年月日：1996年6月20日<br>血液型：O<br>出身地：福岡県<br>身長：164cm<br>趣味：映画鑑賞・可愛いものを見ること・アイドル鑑賞<br>特技：新体操・ダンス・どこでも眠れること<br>チャームポイント：上向きまつげ",
    },
    {
        id:4,
        name_cn: "堺 萌香",
        position_cn: "四期生 Team TII 1998年8月25日 福岡県",
        img_sm:"./img/hkt_pic/team_m4.png",
        img_lg:"./img/hkt_pic/team_4.png",
        alt_cn:"堺 萌香 - 四期生 Team TII 1998年8月25日 福岡県",
        introdution_cn:"MOEKA SAKAI<br>Team TII<br>ニックネーム：おいもちゃん<br>生年月日：1998年8月25日<br>血液型：A<br>出身地：福岡県<br>身長：148cm<br>趣味：筑後地方巡り・朝ごはん作り<br>特技：少林寺拳法・手話<br>チャームポイント：ふたつに割れた耳たぶ",
    },
    {
        id:5,
        name_cn: "地頭江 音々",
        position_cn: "四期生 Team KIV 2000年9月27日 宮崎県",
        img_sm:"./img/hkt_pic/team_m5.png",
        img_lg:"./img/hkt_pic/team_5.png",
        alt_cn:"地頭江 音々 - 四期生 Team KIV 2000年9月27日 宮崎県",
        introdution_cn:"NENE JITOE<br>Team KIV<br>ニックネーム：ねねちゃん<br>生年月日：2000年9月27日<br>血液型：不明<br>出身地：宮崎県<br>身長：156cm<br>趣味：動画鑑賞・断捨離・読書<br>特技：テニス<br>チャームポイント：くっきり二重",
    },
    {
        id:6,
        name_cn: "豊永 阿紀",
        position_cn: "四期生 Team H 1999年10月25日 福岡県",
        img_sm:"./img/hkt_pic/team_m6.png",
        img_lg:"./img/hkt_pic/team_6.png",
        alt_cn:"豊永 阿紀 - 四期生 Team H 1999年10月25日 福岡県",
        introdution_cn:"AKI TOYONAGA<br>Team H<br>ニックネーム：あき<br>生年月日：1999年10月25日<br>血液型：B<br>出身地：福岡県<br>身長：158cm<br>趣味：不動産サイトを見ること・読書・写真撮影・サッカー観戦・セルフネイル<br>特技：資格取得<br>チャームポイント：広いおでこと三重まぶた",
    },
    {
        id:7,
        name_cn: "松本 日向",
        position_cn: "四期生 Team TII 2000年12月11日 大阪府",
        img_sm:"./img/hkt_pic/team_m7.png",
        img_lg:"./img/hkt_pic/team_7.png",
        alt_cn:"松本 日向 - 四期生 Team TII 2000年12月11日 大阪府",
        introdution_cn:"HINATA MATSUMOTO<br>Team TII<br>ニックネーム：ひなた<br>生年月日：2000年12月11日<br>血液型：AB<br>出身地：大阪府<br>身長：165cm<br>趣味：パン屋さん巡り・食べること<br>特技：けん玉<br>チャームポイント：陽気な性格・横顔",
    },
    {
        id:8,
        name_cn: "工藤 陽香",
        position_cn: "五期研究生 2006年4月21日 福岡県",
        img_sm:"./img/hkt_pic/team_m8.png",
        img_lg:"./img/hkt_pic/team_8.png",
        alt_cn:"工藤 陽香 - 五期研究生 2006年4月21日 福岡県",
        introdution_cn:"HARUKA KUDO<br>研究生<br>ニックネーム：はるちゃん<br>生年月日：2006年4月21日<br>血液型：不明<br>出身地：福岡県<br>身長：152cm<br>趣味：スライムを触ること<br>特技：スライム作り・水泳・バドミントン<br>チャームポイント：長いまつげ",
    },
]