// 列表只收集站内页面，name与html文件名一致。
var newsData = [
  // {
  //   id: 10,
  //   title: '',
  //   news_date: '2021-00-00',
  //   name: '',
  //   summary: '',
  //   status: 1,
  //   img_src: './img/.jpg(png)',
  //   source_url: './p/.html',
  // },
  {
    id: 9,
    title: 'IDM下载工具绿色版',
    news_date: '2021-04-26',
    name: 'idm',
    summary: '',
    status: 1,
    img_src: './img/paper_pic/idm-c.png',
    source_url: './p/idm.html',
  },
  {
    id: 8,
    title: '5种AE角色绑定动画脚本介绍对比',
    news_date: '2021-04-14',
    name: 'motion-rig',
    summary: '',
    status: 1,
    img_src: './img/index_pic/motion-rig.png',
    source_url: './p/motion-rig.html',
  },
  {
    id: 7,
    title: '专业软件插件识别检索列表',
    news_date: '2020-11-12',
    name:'soft-list',
    summary: '',
    status: 1,
    img_src: './img/index_pic/soft-list.png',
    source_url: './p/soft-list.html',
  },
  {
    id: 6,
    title: '开源全能三维软件Blender 2.9.X发布',
    name: 'blender-info',
    news_date: '2020-09-02',
    summary: '',
    status: 1,
    img_src: './img/more_pic/news20191125.jpg',
    source_url: '/p/blender-info.html',
  },
  {
    id: 5,
    title: '2020年免费商用字体收集',
    name: 'free-font',
    news_date: '2020-01-08',
    summary: '',
    status: 1,
    img_src: './img/more_pic/news20200108.jpg',
    source_url: '/p/free-font.html',
  },
  {
    id: 4,
    title: '用于取代迅雷的BT下载软件介绍',
    name: 'bt-soft',
    news_date: '2019-12-28',
    summary: '',
    status: 1,
    img_src: './img/more_pic/news20191228.jpg',
    source_url: './p/bt-soft.html',
  },
  {
    id: 3,
    title: '常用AE动态图形动画脚本',
    name:'ae-motion',
    news_date: '2019-11-27',
    summary: '',
    status: 1,
    img_src: './img/index_pic/p02.jpg',
    source_url: './p/ae-motion.html',
  },
  {
    id: 2,
    title: 'Adobe数字媒体制作软件下载',
    name: 'adobe-dl',
    news_date: '2019-11-02',
    summary: '',
    status: 1,
    img_src: './img/index_pic/adobe.jpg',
    source_url: './p/adobe-dl.html',
  },
  {
    id: 1,
    title: '三种不同的AE粒子插件',
    name: 'particular',
    news_date: '2019-10-12',
    summary: '',
    status: 1,
    img_src: './img/index_pic/p01.jpg',
    source_url: './p/particular.html',
  },
];
